### ISSUE TITLE
[ED2] Chp 2 vs. Chp 3 content on single numerical variable

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroStat/randomization-and-simulation#2]
@beanumber @andrewpbray

Can you clarify which chapter has the single numerical variable content? Both of you mention it. I'm talking about things like a histogram, skewness, etc. I'll move around book files accordingly.

**Comment by beanumber** [comment]
I believe that is in @andrewpbray chapter (i.e. - Chapter 2).

**Comment by mine-cetinkaya-rundel** [comment]
Ok good, that's where I have it. @beanumber and @andrewpbray, can you make that clear on the outline document?

I suppose it's generally a good idea to solidify the outline as we're going through and creating content. It will be a good way to then check we didn't miss anything.
