### ISSUE TITLE
global settings

### ISSUE THREAD

**Issue by hardin47** [OpenIntroStat/randomization-and-simulation#26]
is there any reason not to do a global `message = FALSE` for all the R chunks?

![image](https://user-images.githubusercontent.com/7210585/86849569-bb4efd00-c064-11ea-846d-64d8ccc5cc00.png)

**Comment by mine-cetinkaya-rundel** [comment]
Yeah, no reason not to. Other than it keeps me honest while writing, but I think it's more of a hassle so we can add to `common.R`.
