### ISSUE TITLE
R dataset marioKart referred to as mario_kart in book

### ISSUE THREAD

**Issue by gregrs-uk** [OpenIntroStat/randomization-and-simulation#8]
A small problem, but the R dataset `marioKart` available in the `openintro` package is referred to as `mario_kart` within the text of the book. It would be clearer if the names were standardised.

Thank you very much for writing the book and releasing it openly.

**Comment by mine-cetinkaya-rundel** [comment]
Thanks @gregrs-uk for this, and sorry about the way late response as we pick this project back up. The `openintro` package has been updated at https://github.com/openintrostat/openintro and uses `mariokart`. We'll make sure the references are consistent in the book, agreed that this is important!
